name: Meu Workflow

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  executar_codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v2
      - name: Executar script Python
        run: readme.md

